# Generated by Django 3.0.3 on 2020-06-09 01:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_Complain', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComplainForm',
            new_name='UserComplain',
        ),
    ]
