# Generated by Django 3.0.3 on 2020-06-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Complain', '0003_auto_20200608_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomplain',
            name='your_complain',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
